rem BDO_GetRemovedLine.exe BDOLanguage_497\languagedata_en.txt BDOLanguage_488\languagedata_en.txt languagedata_en_removed_497.txt
rem BDO_GetRemovedLine.exe BDOLanguage_510\languagedata_en.txt BDOLanguage_497\languagedata_en.txt languagedata_en_removed_510.txt
BDO_GetRemovedLine.exe BDOLanguage_515\languagedata_en.txt BDOLanguage_510\languagedata_en.txt languagedata_en_removed_515.txt